basic:
  name: Yedhu Krishnan V P
  designation: Software Engineer
  email: yedhukrishnan@yahoo.com
  phone: +91 8547606599
  website: http://dreamlander.in
online_handles:
  twitter: yedhukrishnan
  github: yedhukrishnan
  facebook: yedhukrishnan
  linkedin: yedhukrishnan
skills:
  - title: Programming
    contents:
      - Ruby
      - Java
      - Python
      - HTMP/HTML5/CSS
      - Javascript
      - C/C++
      - Elixir
  - title: Web Frameworks & Technologies
    contents:
      - Ruby on Rails
      - Backbone JS
      - Sails JS
      - Android
work_experience:
  - company: Multunus Software
    time_span: Jun 2013 - present
    designation: Product Developer
    website: http://multunus.com
    summary: Web/mobile development with an agile team
    responsibilities:
      - Frontend and backend development
      - Android application development
      - Test Driven Developent & pair programming
      - Contribute to the community
projects:
  - name: OneMDM
    role: Developer
    time_span: Oct 2014 - Jan 2015
    summary: Open source Mobile Device Management (MDM) solution
    bullet_points:
      - Sails JS server & Android client
      - Ability to view device reports & execute shell scripts remotely from the server

  - name: Read
    role: Developer
    time_span: Feb 2015 - current
    website: http://github.com/yedhukrishnan/read
    summary: A hackernews-like site where users can post articles and others can read and upvote it
    bullet_points:
      - Ruby on Rails
      - Inspired from hackernews

  - name: Resume Builder
    role: Developer
    time_span: Mar 2015 - current
    website: http://github.com/yedhukrishnan/resume-builder
    summary: A tool to build online resume from provided data
    bullet_points:
      - Ruby
      - The tool is used to create this resume
education:
  - institution: Federal Institute of Science and Technology (FISAT), Kochi, Kerala, India
    course: B.Tech (Computer Science and Engineering)
    time_span: 2009 - 2013
interests:
  - Machine learning
  - Reading & writing
  - Movies
